MetalBake/MetalBake.Web/Models/ChangeForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class ChangeForm
    {
        public decimal Amount { get; set; }
        public decimal Total { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/ChangeView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class ChangeView
    {
        public decimal Change { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/ItemPrice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class ItemPrice
    {
        public string ItemId { get; set; }
        public decimal Price { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/ItemStock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class ItemStock
    {
        public string ItemId { get; set; }
        public int Stock { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/ItemsList.cs
using MetalBake.core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class ItemsList
    {
        public List<Item> ListOfItems { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/OrderForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class OrderForm
    {
        public string ItemId { get; set; }
        public int Quantity { get; set; }
    }
}

MetalBake/MetalBake.Web/Models/OrderView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MetalBake.Web.Models
{
    public class OrderView
    {
        public List<string> Summary { get; set; }
        public List<string> Errors { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

MetalBake/MetalBake.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetalBake.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MetalBake/MetalBake.Web/Controllers/OrderController.cs
using MetalBake.ApplicationServices;
using MetalBake.core.Models;
using MetalBake.core.Services;
using MetalBake.infra;
using MetalBake.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetalBake.Web.Controllers
{
    public class OrderController : Controller
    {
        private IItemService _itemService;
        private IOrderService _orderService;

        public OrderController()
        {
            _itemService = new ItemService();
            _orderService = new OrderService();
        }

        // GET: Order
        public ActionResult Index()
        {
            ItemsList itemsList = new ItemsList();
            itemsList.ListOfItems = _itemService.GetAllItems();
            return View(itemsList);
        }

        public ActionResult AddToCart(OrderForm orderForm)
        {
            List<Tuple<string, int>> order;
            if (HttpContext.Session["items"] == null)
            {
                order = new List<Tuple<string, int>>();
            }
            else
            {
                order = HttpContext.Session["items"] as List<Tuple<string, int>>;
            }
            order.Add(new Tuple<string, int>(orderForm.ItemId, orderForm.Quantity));

            HttpContext.Session["items"] = order;
            return View();
        }

        public ActionResult MakeAnOrder(List<Tuple<string, int>> items)
        {
            List<Tuple<string, int>> orderForms = HttpContext.Session["items"] as List<Tuple<string, int>>;
            Order order = _orderService.CreateOrder(orderForms);
            List<string> errors = _orderService.ProcessOrder(order);

            HttpContext.Session["items"] = null;

            OrderView view = new OrderView { Summary = order.GetSummary(), Errors = errors, TotalPrice = order.CalculateOrderPrice() };
            return View(view);
        }

        public ActionResult GiveChange(ChangeForm changeForm)
        {
            decimal change = changeForm.Amount - changeForm.Total;
            ChangeView view = new ChangeView { Change = change };
            return View(view);
        }
    }
}

MetalBake/MetalBake.Web/Controllers/PriceController.cs
using MetalBake.core.Services;
using MetalBake.infra;
using MetalBake.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetalBake.Web.Controllers
{
    public class PriceController : Controller
    {
        private IPriceService _priceService;

        public PriceController()
        {
            _priceService = new PriceService();
        }

        // GET: Price
        public ActionResult Index()
        {
            List<ItemPrice> prices = _priceService.GetAllPrices().Select(item => new ItemPrice { ItemId = item.ItemId, Price = item.Price }).ToList(); ;
            return View(prices);
        }

        public ActionResult Edit(string itemId)
        {
            ItemPrice item = new ItemPrice { ItemId = itemId, Price = _priceService.GetItemPrice(itemId) };
            return View(item);
        }

        public ActionResult SetNewPrice(ItemPrice item)
        {
            _priceService.UpdateItemPrice(item.ItemId, item.Price);
            return Redirect("Index");
        }
    }
}

MetalBake/MetalBake.Web/Controllers/StockController.cs
using MetalBake.core.Services;
using MetalBake.infra;
using MetalBake.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MetalBake.Web.Controllers
{
    public class StockController : Controller
    {
        private IStockService _stockService;

        public StockController()
        {
            _stockService = new StockService();
        }

        // GET: Stock
        public ActionResult Index()
        {
            List<ItemStock> stock = _stockService.GetAllStock().Select(item => new ItemStock { ItemId = item.ItemId, Stock = item.Stock }).ToList();
            return View(stock);
        }

        public ActionResult Edit(string itemId)
        {
            ItemStock item = new ItemStock { ItemId = itemId, Stock = _stockService.GetItemStock(itemId) };
            return View(item);
        }

        public ActionResult SetNewStock(ItemStock item)
        {
            _stockService.SetItemStock(item.ItemId, item.Stock);
            return Redirect("Index");
        }
    }
}

MetalBake/MetalBake.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <span class="metal-title">Metal bakÀ</span>
    <p>@Html.ActionLink("Iniciar pedido", "Index", "Order", null, new { @class = "btn  btn-primary btn-lg" })</p>
</div>

MetalBake/MetalBake.Web/Views/Order/AddToCart.cshtml
@{
    ViewBag.Title = "AddToCart";

}

<div class="alert alert-success" style="margin-top: 50px" role="alert">
    Añadido al Carrito
</div>
@Html.ActionLink("Añadir más", "Index", "Order", null, new { @class = "btn btn-link" })

@Html.ActionLink("Hacer pedido", "MakeAnOrder", "Order", null, new { @class = "btn btn-primary" })

MetalBake/MetalBake.Web/Views/Order/GiveChange.cshtml
@model MetalBake.Web.Models.ChangeView

@{
    ViewBag.Title = "ChangeView";
}

@if (Model.Change >= 0)
{
    <h2>Gracias por tu compra</h2>
    <h3>Tu cambio es @Model.Change€</h3>

}
else
{
    <div class="alert alert-danger"><strong>No se ha introducido suficiente dinero. Faltan @Math.Abs(Model.Change) €</strong></div>

}

MetalBake/MetalBake.Web/Views/Order/Index.cshtml
@model MetalBake.Web.Models.ItemsList
@{
    ViewBag.Title = "Index";
}

<h2>Listado de productos</h2>
@using (Html.BeginForm("AddToCart", "Order"))
{

    <div class="form-inline">
        <select name="itemId" class="form-control">
            @foreach (var item in Model.ListOfItems)
            {
                <option value="@item.ItemId">@item.Name Precio: @item.Price Stock: @item.Stock </option>
            }
        </select>
        <input type="number" name="Quantity" class="form-control" />
        <input type="submit" value="Añadir al carrito" class="btn btn-primary" />
    </div>
}

MetalBake/MetalBake.Web/Views/Order/MakeAnOrder.cshtml
@model MetalBake.Web.Models.OrderView

@{
    ViewBag.Title = "MakeAnOrder";
}

@if (Model.Errors == null)
{
    <h2> Resumen de pedido </h2>
    <ul>
        @foreach (var item in Model.Summary)
        {
            <li>@item </li>
        }
    </ul>

    using (Html.BeginForm("GiveChange", "Order"))
    {
        <h2>Pagar pedido</h2>
        <p>Introduce cantidad para pagar</p>
        <input type="hidden" name="Total" value="@Model.TotalPrice" />
        <div class="form-inline">
            <input type="number" class="form-control" name="Amount" />
            <input type="submit" value="Calcular cambio" class="btn btn-primary" />
        </div>
    }

}
else
{

    <div class="alert alert-danger" role="alert">
        <p><strong>Error</strong> No se ha podido procesar tu pedido</p>
        <ul>
            @foreach (var error in Model.Errors)
            {
                <li>@error</li>
            }
        </ul>
    </div>

    @Html.ActionLink("Hacer otro pedido", "Index", "Order", new { @class = "btn btn-primary" })

}

MetalBake/MetalBake.Web/Views/Stock/Edit.cshtml
@model MetalBake.Web.Models.ItemStock
@{
    ViewBag.Title = "Edit";
}

<h2>Editar stock @Model.ItemId</h2>
@using (Html.BeginForm("SetNewStock", "Stock"))
{
    @Html.HiddenFor(item => item.ItemId)
    <div class="form-inline">
        @Html.TextBoxFor(item => item.Stock, new { @class = "form-control" })
        <input type="submit" value="Cambiar" class="btn btn-primary" />
    </div>
}

MetalBake/MetalBake.Web/Views/Stock/Index.cshtml
@model List<MetalBake.Web.Models.ItemStock>
@{
    ViewBag.Title = "Index";
}

<h2>Inventario</h2>
<table class="table">
    <tr>
        <th>Producto</th>
        <th>Stock</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ItemId</td>
            <td>@item.Stock</td>
            <td>@Html.ActionLink("Editar stock", "Edit", "Stock", new { itemId = item.ItemId }, null)</td>
        </tr>
    }
</table>